# Generated by Django 5.2 on 2025-04-30 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='proof_image',
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
