# Generated by Django 5.2 on 2025-04-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_trip_duration_minutes_remove_trip_proof_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transport_mode',
            field=models.CharField(choices=[('public_transport', 'Public Transport'), ('carpool', 'Carpool'), ('personal_vehicle', 'Personal Vehicle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20),
        ),
    ]
