# Generated by Django 5.2 on 2025-05-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_employerprofile_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
