# Generated by Django 5.2 on 2025-04-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='registration_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
